
default: &default
  adapter: postgresql
  user: <%= Rails.application.secrets.database_user %>
  password: <%= Rails.application.secrets.database_password %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: myflix_development

test:
  <<: *default
  database: myflix_test
  
production:
  <<: *default
  database: myflix_production

