# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b07b9f8555d1233a0f25f1ce896f7bd56773c236ff061cc772b13ce891f04e8c8fd0c8551655bbf9ee0490dacc531fabade7ce578c3370037fd8691158b54989
  database_user: <%= ENV["DATABASE_USER"] %>
  database_password: <%= ENV["DATABASE_PASSWORD"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  
test:
  secret_key_base: 420aea731489149c1240368040433d700e4a8ea811feadc134b8b61059bd1d943d74a18fa1b1423f6a5e5161395cca19262efc63bb37aef2e4ab8102b8e12c8c
  database_user: <%= ENV["DATABASE_USER"] %>
  database_password: <%= ENV["DATABASE_PASSWORD"] %>
  aws_access_key_id: test-does-not-use-s3
  aws_secret_access_key: test-does-not-use-s3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["MYFLIX_SECRET_KEY_BASE"] %>
  database_user: <%= ENV["DATABASE_USER"] %>
  database_password: <%= ENV["DATABASE_PASSWORD"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  